### ISSUE TITLE
Massive refactoring required...

### ISSUE THREAD

**Issue by jokillsya** [Simmetrics/simmetrics#1]
When I initially cloned this project from Sourceforge, I didn't anticipate that the codebase would be this archaic, a large number of unit-tests simply failed miserably, there are loads of places where generics among other post Java 5 language features would have been a much better fit, the object hierarchy isn't really what it could be - I noticed a lot of places where a hell of a lot of performance could be squeezed out of a number of metrics and the lack of generally accepted good Java patterns and practises makes my stomach crawl. So - I thought the first step is to get proper post Java 5 language features into the existing codebase - clean up the code - COMMENT the damn code and then see if we can re-engineer the Object hierarchy to make a bit more sense to an API implementor...

**Comment by mpkorstanje** [comment]
Hi! I'm almost through a major re-factoring. Though I started working from a different fork of SimMetrics.

What I've done so far.

1. Removed loads and loads of of crud.
2. Simplified the interfaces.
3. Cleaned up some of the simpler algorithms.
4. Moved Chapmans algorithms and the horrible TagLink implementation into their own projects.

There is a general work-flow to comparing strings. Strings are always simplified to a normal form, depending on the algorithm tokenized to a set or a list or not tokenized at all and then compared. 

When doing batch comparisons of one string against a large set I also found caching tokenization results to be useful. 

For all these I added support. 

5. Split metrics into string, list and set metrics (and this really cleaned up some crud).
6. Created a DSL to turn list and set metrics into string metrics by adding tokenizers. 
7. The DSL also supports token filtering without adding the isWord() check in every tokenizer.
8. The DSL makes it easy to add caching and simplification.

		StringMetric metric = new StringMetricBuilder()
				.with(new CosineSimilarity<String>())
				.simplify(new CaseSimplifier.Lower())
				.simplify(new NonWordCharacterSimplifier())
				.tokenize(new WhitespaceTokenizer())
				.filter(not(in(dictionary)))
				.build();

Documentation is lagging behind the latest re-factoring a bit but that will catch up once I'm satisfied with the DSL. I'm also not happy about the way caching expressed in the DSL but I'll get to that too.

Would you be interested in putting it up here and helping along?

https://github.com/mpkorstanje/simmetrics
