### ISSUE TITLE
Is there a way to simplify tokens AFTER tokenizer ?

### ISSUE THREAD

**Issue by ijabz** [Simmetrics/simmetrics#18]
StringMetric metric =
            with(new CosineSimilarity<String>())
            .simplify(new Case.Lower(Locale.ENGLISH))
            .simplify(new NonWordCharacter())
            .tokenize(new Whitespace())
            .build();

The example show simplification on the input BEFORE tokenization, but if we want to do simplication on a word not sentence basis it would much easier if the simplifier could just work on a token rather than the whole sentence, by simplifying  AFTER tokenization (For example I would like to write a simplifier that removed "'s" from the end of words)

Using Lucene Analyzers syntax, your simplifiers wortk like a NormalizeCharMap , tokenize is like a Tokenizer but there is no support for Filters.

**Comment by mpkorstanje** [comment]
There isn't. Yet. Not in the StringMetricsBuilder anyway. 

I did I re-factor the original library so that the list and set metrics would allow you to compare arbitrary lists with elements of the same type. the StringMetricsBuilder was added to maintain feature parity, not really for advanced processing.

In the immediate term you can work around this short coming by using the components themselves.

```
SetMetric<String> metric = new CosineSimilarity<String>();
Tokenizer t = new Whitespace();
Set<String> aTokens =  t.tokenizeToSet("hello worlds");
Set<String> bTokens =  t.tokenizeToSet("hello other worlds!");

//apply filtering and transforms on  tokens here

metric.compare(aTokens, bTokens);

```		

But it shouldn't be too hard to add steps that simplify tokens.

```
StringMetric metric =
with(new CosineSimilarity())
.simplify(new Case.Lower(Locale.ENGLISH))
.simplify(new NonWordCharacter())
.tokenize(new Whitespace())
.filter(new IsLongWordWord())
.simplify(new RemovePossessiveS)
.filter(new IsNoun())
.simplify(new PresentPerfectForm())
.build();
```
Where IsLongWordWord and IsNoun are Guava filters and RemovePossessiveS and PresentPerfectForm are Guava functions. Would have to keep in mind to create a new Set after each transformation though to avoid duplicates.

If you don't mind me asking. Why aren't you using Lucence though? It's a bit more mature.

**Comment by ijabz** [comment]
thanks Im using this lib because I'm just trying to compare two strings rather than search for x in a number of strings  (documents) whihc is what lucene is for.

**Comment by ijabz** [comment]
I understand the workound you provide, except how would I adapt if I still want to so some simplication BEFORE tokenization as well as AFTER tokenizaton.

**Comment by mpkorstanje** [comment]
You can do it like this. But it gets a bit clunky if you want to do allot.

```
SetMetric<String> metric = new CosineSimilarity<String>();
Tokenizer t = new Whitespace();
Simplifier s = new Case.Lower();

String a = "hello worlds";
String b = "hello other worlds!";

String aSimple = s.simplify(a);
String bSimple = s.simplify(b);

// optionally repeat with other simplifiers

Set<String> aTokens =  t.tokenizeToSet(aSimple);
Set<String> bTokens =  t.tokenizeToSet(bSimple);

//apply filtering and transforms on  tokens here

metric.compare(aTokens, bTokens);
```

**Comment by mpkorstanje** [comment]
Just committed 3806bb5f647ea7988c3acba527ead846f63f1797 which adds the transform step to the builder. After the first tokenize step, you can chain any  tokenize, filter or transform step indefinitely.

```
StringMetric metric = with(new CosineSimilarity<String>())
		.tokenize(new Whitespace())
		.filter(longWords())
		.transform(removePossessiveS())
		.filter(longWords())
		.tokenize(new QGram(3))
		.transform(...)
		.filter(..)
		.filter(..)
		.transform(...)
		.build();
```


I hope you don't mind building from source though. The current chaining method isn't as efficient as it can be. I want to have a look at that before I push a new release to maven central.

**Comment by ijabz** [comment]
Thanks I dont mind building from src but I am having git problems, git pull brought nothing new, git checkout develop and then git pull didnt either - not sure what I am doing wrong

**Comment by mpkorstanje** [comment]
Are you pulling from Simmetrics or your own clone?

**Comment by ijabz** [comment]
from simmetrics, i started with git clone https://github.com/Simmetrics/simmetrics.git

**Comment by mpkorstanje** [comment]
I really don't know. The check ins are in the repo. :S

**Comment by mpkorstanje** [comment]
I've just deployed version 3.2.0 of Simmetrics. It should be up on Maven Central in a few hours.

The StringMetricsBuilder can transform tokens after the tokenization step. Repeated filtering and transform operations are sqaushed together. Either with Guava's `Predicates.compose` and `Functions.compose` or by internally passing the Filtered and Transformed Collections rather then creating new lists/sets for each step.
