### ISSUE TITLE
java.util.zip.ZipException: duplicate entry: com/google/common/reflect/TypeToken$TypeCollector$ForwardingTypeCollector.class

### ISSUE THREAD

**Issue by MrBrightside29** [Simmetrics/simmetrics#19]
Hi,

When building my project I get this error:

```
Error:Execution failed for task ':app:packageAllDebugClassesForMultiDex'.
> java.util.zip.ZipException: duplicate entry: com/google/common/reflect/TypeToken$TypeCollector$ForwardingTypeCollector.class
```
What should I do?

Thanks in advance.

**Comment by mpkorstanje** [comment]
Could you give me some background on what you're doing? I don't recognize this build system. 

It looks like you're trying to aggregate all classes from different jars into a single zip. Simmetrics has a dependency on Google's Guava, com.google.guava:guava:18.0 to be exact. Would your project happen to be using a different version of Guava? Or perhaps you have another dependency with a dependency on guava that your packer can't handle?

But it looks like you are building your own project. I can't really help you with that.

**Comment by MrBrightside29** [comment]
Sorry for the missing info. It's gradle and I'm using it in a Android application I'm developing. But don't worry, I've just solved the problem by excluding the Guava dependency from your library.

compile ('com.github.mpkorstanje:simmetrics-core:3.2.1') { exclude group: 'com.google.guava' }

Thanks anyway for your help!

**Comment by mpkorstanje** [comment]
No problem.

**Comment by praslnx8** [comment]
I have sugarOrm. I tried compile ('com.github.satyan:sugar:1.4')
            {
                exclude group: 'com.google.guava'
            }

This works fine.
