### ISSUE TITLE
Can't download using maven

### ISSUE THREAD

**Issue by ruipserra** [Simmetrics/simmetrics#20]
I added the following to my pom.xml

```
<dependency>
  <groupId>com.github.mpkorstanje</groupId>
  <artifactId>simmetrics</artifactId>
  <version>4.1.0</version>
</dependency>
```

Running `mvn install` fails with:

```
[ERROR] Failed to execute goal on project my-project: Could not resolve dependencies for project my-project:my-project:jar:0.1.0-SNAPSHOT: Could not find artifact com.github.mpkorstanje:simmetrics:jar:4.1.0 in central (https://repo1.maven.org/maven2/) -> [Help 1]
```

What am I doing wrong?

**Comment by mpkorstanje** [comment]
You're trying to add a dependency on a pom project. You'll have to use simmetrics-core to get the jars.

    <dependency>
        <groupId>com.github.mpkorstanje</groupId>
        <artifactId>simmetrics-core</artifactId>
        <version>4.1.0</version>
    </dependency>

When you check the central repository you can tell because it only lists pom behind simmetrics while it lists jar behind simmetrics-core.

![image](https://cloud.githubusercontent.com/assets/6946919/12489542/1f04a8c0-c071-11e5-87af-3b538046af53.png)

**Comment by ruipserra** [comment]
Doh! That did the trick, thank you.

**Comment by mpkorstanje** [comment]
No problem. 

Could you tell me where you found Simmetrics? In hind sight the module naming could have been done better but that would be a long term change. I can fiddle a bit with the project descriptions on the short term.

**Comment by ruipserra** [comment]
I was googling around for string similarity matching and landed on a StackOverflow answer mentioning [this link](http://web.archive.org/web/20081224234350/http://www.dcs.shef.ac.uk/~sam/stringmetrics.html#compare). Another google query led me here.

Actually, I was thinking of adding a small section with

```
<dependency>
    <groupId>com.github.mpkorstanje</groupId>
    <artifactId>simmetrics-core</artifactId>
    <version>4.1.0</version>
</dependency>
```

to the project readme. Then again, there's already a maven central badge, I just happened to miss it.

**Comment by mpkorstanje** [comment]
You're not the first person to make this mistake. So I'd like to tease this apart a bit more. If you don't mind indulging a perfectionist of-course. 

After being unable to find the maven dependency on the github page, what did you search for and what did you find?

**Comment by ruipserra** [comment]
I [searched in maven central](http://search.maven.org/#search%7Cga%7C1%7Csimmetrics) to make sure it was registered there. Still unable to fetch the dependency, I tried adding the sonatype repos mentioned in the `pom` file (obviously with no success either). Then I decided to open this issue. 

It must be said that I'm a maven noob. I haven't coded Java for some time, and I was actually trying to play around with Simmetrics in a Clojure project, using [Leiningen](https://github.com/technomancy/leiningen).

**Comment by mpkorstanje** [comment]
Cheers!

Having little experience with maven makes you the right test audience in this case. Most users of a library are not going to be experts in dependency management software. So I feel that your first guess should have been the right one especially if making the right choice requires knowledge of rather domain specific fine print.

You could have ended up worse though. The other person reporting the same problem used google and ended up on mvnrepository which doesn't even hint that there are other artifacts.

![screenshot from 2016-01-25 20-51-02](https://cloud.githubusercontent.com/assets/6946919/12627370/bd9099ce-c53d-11e5-9d16-17adc278eac1.png)

Lesson learned again I guess. Naming things is hard. Not sure if I can/will fix this though.

Anyway goodluck with your project.
