### ISSUE TITLE
Maven

### ISSUE THREAD

**Issue by micaelaoriolo** [Simmetrics/simmetrics#21]
Hi! How can I use this library with Maven? I mean, adding the correct dependency to my project's POM.
Thanks!

**Comment by mpkorstanje** [comment]
Hey. You can click the maven central badge. It will always take you to the latest release.

![screenshot from 2016-04-24 21-19-37](https://cloud.githubusercontent.com/assets/6946919/14769844/4f06570e-0a62-11e6-98cf-9321838f21de.png)

Then you include the following into the dependencies section of your pom:

```
<dependency>
    <groupId>com.github.mpkorstanje</groupId>
    <artifactId>simmetrics-core</artifactId>
    <version>4.1.0</version>
</dependency>
```

**Comment by micaelaoriolo** [comment]
Thanks a lot! I didn't know about that badge :)

**Comment by micaelaoriolo** [comment]
(I didn't realize that this question was made before, sorry. I'm still a newby with github issues.)
