### ISSUE TITLE
Character encoding in source files

### ISSUE THREAD

**Issue by ltung** [Simmetrics/simmetrics#23]
I tried to build with maven but it said it failed test:

Failed tests:   shouldTokenizeToSet(org.simmetrics.tokenizers.QGramTest$QGram3): He??llo did not tokenize correctly expected:<[e??l, ??ll, He??, llo]> but was:<[He?, e??, ??l, llo, ?ll]>
  shouldTokenizeToMutiset(org.simmetrics.tokenizers.QGramTest$QGram3): He??llo did not tokenize correctly expected:<[e??l, ??ll, He??, llo]> but was:<[He?, e??, ??l, llo, ?ll]>
  shouldTokenizeToList(org.simmetrics.tokenizers.QGramTest$QGram3): He??llo did not tokenize correctly expected:<[He??, e??l, ??ll, llo]> but was:<[He?, e??, ??l, ?ll, llo]>
....
....

Can the author successfully build the .jar ?

**Comment by mpkorstanje** [comment]
Travis doesn't seem to have any problems. Looks like it might be an encoding issue on your end. What are the question marks?

**Comment by ltung** [comment]
Those are really questions marks  in the output. I am new to maven. Should I try Travis instead?

**Comment by mpkorstanje** [comment]
Naw. Travis is the build server. Its an independent third party that verifies every thing is correct.

I'll have a look at that test on monday. For now you may want to ignore it. Comment it out or add an @Ignore tag if you need to get the build working.

What operating system are you using btw?

Cant really help you with maven. If you want to use it as a dependecy just include it. Search the web for tutorials.

**Comment by mpkorstanje** [comment]
Naw. Travis is the build server. Its an independent third party that verifies every thing is correct.

I'll have a look at that test on monday. For now you may want to ignore it. Comment it out or add an @Ignore tag if you need to get the build working.

What operating system are you using btw?

Cant really help you with maven. If you want to use it as a dependecy just include it. Search the web for tutorials.

**Comment by ltung** [comment]
I am using Windows 10 Pro 64-bit. I am planning to build it into a .jar and use interface bridge (possibility, ikvm) to interface to C# and use it on my suppose Web App.

**Comment by mpkorstanje** [comment]
Definiltly an encoding issue then. Those specific test case are aimed at just that. I'll have to check if the source has the proper encoding.

You can ignore it for now.

Beyond that. The compiled jar is available on maven central. Usin that directly rather then building from source makes it easier in the long run to maintain the project.

**Comment by ltung** [comment]
Ok. Tks. Appreciate your prompt response.

**Comment by mpkorstanje** [comment]
Could you try and build the develop branch? 

It should have been fixed there. I won't fix master until more features have been added.

**Comment by ltung** [comment]
I have just cloned the develop branch and it built successfully. Thanks!
