### ISSUE TITLE
Would be use to be able to run simplify() (NOT transform()) AFTER a tokenizer step

### ISSUE THREAD

**Issue by ijabz** [Simmetrics/simmetrics#25]
To understand why I would like to be able to apply simplify() rather than transform() Ill explain my use case.

I am comparing artist credits for a song, in the case of classical music releases the artist credit often contains multiple composers/performers separated by a comma or semicolon. Sometimes composers are given their surname other times their whole names so for the most popular composers I want to simpilify their names.
i.e
beethoven; london symphony orchestra to
ludwig van beethoven, symphony orchestra 

To do this I need to tokenize on ',;' so i can use ClassicalComposerShortner to replace 'ludwig van beethoven' with 'beethoven' by looking up value in a map, but I then want to run my srs simplier which amongst other things remove all punctution with .replaceAll("\\p{Punct}","").. So I want to this to be applied to the whole string not just the tokens, of course I cant do this before I run tokenizers because at that point I need the punctuation in order to tokenize it, and the code doesnt support simplifiers after tokenization.

I suppose I could do this by doing some string processing before passing them tot he metric builder but I wanted to show you a reason why it would be useful to be able to simplify after tokenization to see if this would make sense for the library. After tokenization you no longer have the complete string so I guess what would be needed would be some kind of reversible tokenizer that can tokenize, allow some transforms then untokenize whilst keeping the transform.

```
StringMetric metric = with(new CosineSimilarity<String>())
                .simplify(new EquivalentCharsSimplifier())
                .simplify(Simplifiers.toLowerCase())
                .simplify(Simplifiers.removeDiacritics())
                .tokenize(Tokenizers.pattern("[,;]")) //Multiple artists
                .transform(new ClassicalComposerShortener())
                .simplify(srs)
                .tokenize(Tokenizers.whitespace())
                .filter(not(in(commonWords)))
                .transform(new RemovalPlurals())
                .tokenize(Tokenizers.qGram(2))
                .build();
```

**Comment by mpkorstanje** [comment]
So you want to be able to this transformation?

```java
"ludwig van beethoven, symphony orchestra - opus 5"       //initial string  
["beethoven", "symphony orchestra - opus 5"]              // split on the comma  
["beethoven", "symphony orchestraopus 5"]                 // other punctuation removed  

```
And for that you want to use a Simplifier rather then a function. You could write a simple wrapper and use that to transform your simplifier but I suppose it wouldn't be a bad thing to add  a .transform(Simplifier) method to the builders.

```java
public static Function<String,String> simplifierToFunction(final Simplifier s){
   return new Function<String,String>(){
        public String apply(String token){
          return s.simplify(token);
        }
   }
} 
```

**Comment by ijabz** [comment]
I may have a solution (see end of post) but Im not entirely sure if you have understood my point, I'll try again.

I want to replace certain strings e.g "ludwig van beethoven" with "beethoven", to me this seems like a use of transform(), replacing one token value with another value rather than parsing the whole string to find occurences of "ludwig van beethoven" I would just compare each token.

However "ludwig van beetthoven" is not a final token because I tokenize my white space (and then ngrams but this is irrelevent for this discussion) , so I cant run transform() after whitespace tokenizer. But I could use if I tokenized by (,;), the troiuble is I then cant use my simplifier because that cant after a tokenizer.

This is my simplifier method
```
 public String simplify(String input) {

        if(input==null)
        {
            return null;
        }

        String result =  input
                .replace("[", "(")
                .replace("{", "(")
                .replace("]", ")")
                .replace("}", ")")
                .replace(" & ", " and ")
                .replace("\"", "")
                .replace("'","")
                .replace("-", " ")
                .replace(":", " ")
                .replace(";", " ")
                .replace(",", " ");
        return result.replaceAll("\\p{M}", "").replaceAll("\\p{Punct}","").replaceAll("\\p{Space}"," ").trim();
    }

Having said that perhaps I could rewrite my simplifier so it removed all punctuation except ';' and ',', and then it could be ran before the first tokenizer. Maybe the roles of simplier, transformer just nee dmore explanation.
```

**Comment by mpkorstanje** [comment]
The simplifier works on the string before it is tokenized. The transformer works on the individual tokens that the tokenizer produces. Functionally there is no real difference as both have the signature String -> String.

**Comment by ijabz** [comment]
Yes I understand the difference but has performance implications, for example replacing a token with another value it much more efficient than searching for those tokens in a string if there are many words to search for and replace since the second method requires a regex for each pair using tokens does not.

But I have fixed my particular issue my changing simplifier to 

```
return result.replaceAll("\\p{M}", "")
                .replaceAll("(?![,;])\\p{Punct}", "")
                .replaceAll("\\p{Space}"," ").trim();
               
    }
```
so the , and ; remain so can be tokenized in the first instance based on these, run the transformer and then tokenize again based on white space

**Comment by mpkorstanje** [comment]
```java
Function<String, String> composerNameTransform = new Function<String, String>() {

	@Override
	public String apply(String s) {
		if ("ludwig von beethoven".equals(s)) {
			return "beethoven";
		}

		return s;
	}
};

Predicate<String> commonWords = new Predicate<String>() {
	@Override
	public boolean apply(String s) {
		return !"london".equals(s);
	}
};


StringMetric metric =
		StringMetricBuilder.with(new CosineSimilarity<String>())
				.simplify(Simplifiers.toLowerCase())
				.tokenize(Tokenizers.pattern("[,;]"))
				.transform(composerNameTransform)
				.tokenize(Tokenizers.whitespace())
				.filter(commonWords)
				.tokenize(Tokenizers.qGram(3))
				.build();


System.out.println(metric.compare(
    "Ludwig Von Beethoven; Symphony Orchestra", 
    "beethoven symphony orchestra"));
System.out.println(metric.compare(
    "Ludwig Von Beethoven, London Symphony Orchestra", 
    "beethoven symphony orchestra"));
```

**Comment by ijabz** [comment]
I dont think you are getting my point - which was it would be useful to be able to run a simplifier (not a tranformer) after a tokenization step, but maybe its a silly idea anyway so since Ive solved the issue anyway please dont waste any more time on it.
