### ISSUE TITLE
face detect

### ISSUE THREAD

**Issue by nickl-** [Simmetrics/simmetrics#3]
http://facedetection.jaysalvat.com/

**Comment by mpkorstanje** [comment]
Cool stuff. But that it isn't really about comparing strings. What do you want to do with this?

**Comment by jokillsya** [comment]
Hi.

Our origional idea was to start off with String Metrics and gradually add
all sorts of other similarity metrices which operate over a wider variety
of objects. Similarities between voices, images, videos etc...

**Comment by mpkorstanje** [comment]
Ah that explains.

I did setup the [Metric](https://github.com/Simmetrics/simmetrics/blob/master/simmetrics-core/src/main/java/org/simmetrics/Metric.java) class to compare any two objects of the same type. So accommodating it shouldn't be a problem.

That is, if some does it.

**Comment by jokillsya** [comment]
Unfortunately that won't quite cut it.

One should be able to compare two different images, both have a tree in
common for example...

On Sun, Apr 26, 2015 at 12:16 PM, mpkorstanje <notifications@github.com>
wrote:

> Ah that explains.
>
> I did setup the Metric
> <https://github.com/Simmetrics/simmetrics/blob/master/simmetrics-core/src/main/java/org/simmetrics/Metric.java>
> class to compare any two objects of the same type. So accommodating it
> shouldn't be a problem.
>
> That is, if some does it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Simmetrics/simmetrics/issues/3#issuecomment-96360177>.
>



-- 
Best Regards

Johnathan Botha

**Comment by jokillsya** [comment]
Or the same voice recording with slightly different pitch...

On Sun, Apr 26, 2015 at 12:18 PM, Johnathan Botha <jokillsya@gmail.com>
wrote:

> Unfortunately that won't quite cut it.
>
> One should be able to compare two different images, both have a tree in
> common for example...
>
> On Sun, Apr 26, 2015 at 12:16 PM, mpkorstanje <notifications@github.com>
> wrote:
>
>> Ah that explains.
>>
>> I did setup the Metric
>> <https://github.com/Simmetrics/simmetrics/blob/master/simmetrics-core/src/main/java/org/simmetrics/Metric.java>
>> class to compare any two objects of the same type. So accommodating it
>> shouldn't be a problem.
>>
>> That is, if some does it.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Simmetrics/simmetrics/issues/3#issuecomment-96360177>
>> .
>>
>
>
>
> --
> Best Regards
>
> Johnathan Botha
>
>


-- 
Best Regards

Johnathan Botha

**Comment by mpkorstanje** [comment]
Ah I see. Then we'll have to figure it out what to do with it when it is
coded. :)

**Comment by jokillsya** [comment]
Not at all...

I'm halfway through coding an HMM based speech recognition API for the
C-version. This will be able to identify recordings of voices and correctly
associate them with the correct person - as an example. There are many uses
for such an algorithm. Recognising patterns in images is just as useful for
going through a library of images and identifying all the images with a cat
in them...

On Sun, Apr 26, 2015 at 12:30 PM, mpkorstanje <notifications@github.com>
wrote:

> Ah I see. Then we'll have to figure it out what to do with it when it is
> coded. :)
>
> On 26 April 2015 at 12:19, Johnathan Botha <notifications@github.com>
> wrote:
>
> > Or the same voice recording with slightly different pitch...
> >
> > On Sun, Apr 26, 2015 at 12:18 PM, Johnathan Botha <jokillsya@gmail.com>
> > wrote:
> >
> >
> > > Unfortunately that won't quite cut it.
> > >
> > > One should be able to compare two different images, both have a tree in
> > > common for example...
> > >
> > > On Sun, Apr 26, 2015 at 12:16 PM, mpkorstanje <
> notifications@github.com>
> > > wrote:
> > >
> > >> Ah that explains.
> > >>
> > >> I did setup the Metric
> > >> <
> >
> https://github.com/Simmetrics/simmetrics/blob/master/simmetrics-core/src/main/java/org/simmetrics/Metric.java
> > >
> > >> class to compare any two objects of the same type. So accommodating it
> > >> shouldn't be a problem.
> > >>
> > >> That is, if some does it.
> > >>
> > >> —
> > >> Reply to this email directly or view it on GitHub
> > >> <
> > https://github.com/Simmetrics/simmetrics/issues/3#issuecomment-96360177>
> > >> .
> > >>
> > >
> > >
> > >
> > > --
> > > Best Regards
> > >
> > > Johnathan Botha
> > >
> > >
> >
> >
> > --
> > Best Regards
> >
> > Johnathan Botha
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/Simmetrics/simmetrics/issues/3#issuecomment-96360239
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Simmetrics/simmetrics/issues/3#issuecomment-96361341>.
>



-- 
Best Regards

Johnathan Botha

**Comment by mpkorstanje** [comment]
This has been open for 2 years with no work done. I assume the idea has been abandoned. Doesn't mean we can't include it when some one makes it. But until that happens it seems weird to let that clutter up the issue list.
