### ISSUE TITLE
remove eclipse .classpath .project files and make it maven project

### ISSUE THREAD

**Issue by apivovarov** [Simmetrics/simmetrics#6]
1. I think project should not include IDE specific files to the project.
2. Maven is a de facto standard for organizing java projects.

Developers can run mvn eclipse:eclipse to generate .classpath .project files
Other people prefer M2Eclipse plugin. They do not need to run eclipse:eclipse and their .classpath .project files are very different.
Another people use IDEA.

just refactor project to be a maven project . So, each developer knows how to open maven project in his/her preferred IDE.

3. Try to follow maven folder structure. Put Tests to a separate folder. Tests should not be included to final jar file.

**Comment by mpkorstanje** [comment]
Hi. This project was last updated in 2012. I have contacted Joyskilla but last I heard was that he was preoccupied due to work.

I've been working on a cleanup and fix. Though I started working from a different clone of the original source forge release. It uses maven.

https://github.com/mpkorstanje/simmetrics

**Comment by jokillsya** [comment]
Hi guys. Sorry for being a bit busy. I'll merge some of the code now. I
like a lot of the feedback!

**Comment by jokillsya** [comment]
Ok - I'm back in action...

Would you guys mind submitting a pr?

**Comment by mpkorstanje** [comment]
Hey Jo, I started working off a different tree. I'm looking into how to get it over.

**Comment by mpkorstanje** [comment]
Okay. I can't do a github pull request because we aren't on the same tree. Best I can do is give you a written pull request through `git request-pull 84faf284a6a54ee34ef1661b4533e1aaf7d85ead git@github.com:mpkorstanje/simmetrics.git`

I did a merge of Simmetrics/simmetrics master so the pull should go over al-right.

```
The following changes since commit 84faf284a6a54ee34ef1661b4533e1aaf7d85ead:

  Added move instructions... (2012-10-25 12:30:15 +0200)

are available in the git repository at:

  git@github.com:mpkorstanje/simmetrics.git develop

for you to fetch changes up to e2969978ebd170a6a6dff1f2f016789ff24e7f56:
```

**Comment by jokillsya** [comment]
Hi.

When it comes to actually merging your changes - you're definitely going to
be the expert - especially given the number of changes you seem to have
made. Would it be possible for you to clone the Simmetrics project into a
separate directory, then whack all the files in there and paste all yours
in - then use git format-patch to generate a diff I can pull into the git
tree properly? That way I can also attach your name to the official repo?

On Sat, Feb 21, 2015 at 12:12 AM, mpkorstanje <notifications@github.com>
wrote:

> Okay. I can't do a github pull request because we aren't on the same tree.
> Best I can do is give you a written pull request through git request-pull
> 84faf284a6a54ee34ef1661b4533e1aaf7d85ead git@github.com:
> mpkorstanje/simmetrics.git
>
> I did a merge of Simmetrics/simmetrics master so the pull should go over
> al-right.
>
> The following changes since commit 84faf284a6a54ee34ef1661b4533e1aaf7d85ead:
>
>   Added move instructions... (2012-10-25 12:30:15 +0200)
>
> are available in the git repository at:
>
>   git@github.com:mpkorstanje/simmetrics.git develop
>
> for you to fetch changes up to e2969978ebd170a6a6dff1f2f016789ff24e7f56:
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Simmetrics/simmetrics/issues/6#issuecomment-75329060>.
>



-- 
Best Regards

Johnathan Botha

**Comment by jokillsya** [comment]
Here's a good sample:
https://ariejan.net/2009/10/26/how-to-create-and-apply-a-patch-with-git/

Then just mail me the patches/patch...

On Sat, Feb 21, 2015 at 12:16 AM, Johnathan Botha <jokillsya@gmail.com>
wrote:

> Hi.
>
> When it comes to actually merging your changes - you're definitely going
> to be the expert - especially given the number of changes you seem to have
> made. Would it be possible for you to clone the Simmetrics project into a
> separate directory, then whack all the files in there and paste all yours
> in - then use git format-patch to generate a diff I can pull into the git
> tree properly? That way I can also attach your name to the official repo?
>
> On Sat, Feb 21, 2015 at 12:12 AM, mpkorstanje <notifications@github.com>
> wrote:
>
>> Okay. I can't do a github pull request because we aren't on the same
>> tree. Best I can do is give you a written pull request through git
>> request-pull 84faf284a6a54ee34ef1661b4533e1aaf7d85ead git@github.com:
>> mpkorstanje/simmetrics.git
>>
>> I did a merge of Simmetrics/simmetrics master so the pull should go over
>> al-right.
>>
>> The following changes since commit 84faf284a6a54ee34ef1661b4533e1aaf7d85ead:
>>
>>   Added move instructions... (2012-10-25 12:30:15 +0200)
>>
>> are available in the git repository at:
>>
>>   git@github.com:mpkorstanje/simmetrics.git develop
>>
>> for you to fetch changes up to e2969978ebd170a6a6dff1f2f016789ff24e7f56:
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Simmetrics/simmetrics/issues/6#issuecomment-75329060>
>> .
>>
>
>
>
> --
> Best Regards
>
> Johnathan Botha
>
>


-- 
Best Regards

Johnathan Botha

**Comment by jokillsya** [comment]
This will also make it possible for me to have a good broad overview of the
code changes as distinct from build system changes...

On Sat, Feb 21, 2015 at 12:17 AM, Johnathan Botha <jokillsya@gmail.com>
wrote:

> Here's a good sample:
> https://ariejan.net/2009/10/26/how-to-create-and-apply-a-patch-with-git/
>
> Then just mail me the patches/patch...
>
> On Sat, Feb 21, 2015 at 12:16 AM, Johnathan Botha <jokillsya@gmail.com>
> wrote:
>
>> Hi.
>>
>> When it comes to actually merging your changes - you're definitely going
>> to be the expert - especially given the number of changes you seem to have
>> made. Would it be possible for you to clone the Simmetrics project into a
>> separate directory, then whack all the files in there and paste all yours
>> in - then use git format-patch to generate a diff I can pull into the git
>> tree properly? That way I can also attach your name to the official repo?
>>
>> On Sat, Feb 21, 2015 at 12:12 AM, mpkorstanje <notifications@github.com>
>> wrote:
>>
>>> Okay. I can't do a github pull request because we aren't on the same
>>> tree. Best I can do is give you a written pull request through git
>>> request-pull 84faf284a6a54ee34ef1661b4533e1aaf7d85ead git@github.com:
>>> mpkorstanje/simmetrics.git
>>>
>>> I did a merge of Simmetrics/simmetrics master so the pull should go over
>>> al-right.
>>>
>>> The following changes since commit 84faf284a6a54ee34ef1661b4533e1aaf7d85ead:
>>>
>>>   Added move instructions... (2012-10-25 12:30:15 +0200)
>>>
>>> are available in the git repository at:
>>>
>>>   git@github.com:mpkorstanje/simmetrics.git develop
>>>
>>> for you to fetch changes up to e2969978ebd170a6a6dff1f2f016789ff24e7f56:
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/Simmetrics/simmetrics/issues/6#issuecomment-75329060>
>>> .
>>>
>>
>>
>>
>> --
>> Best Regards
>>
>> Johnathan Botha
>>
>>
>
>
> --
> Best Regards
>
> Johnathan Botha
>
>


-- 
Best Regards

Johnathan Botha

**Comment by jokillsya** [comment]
I'm really excited to be able to collaborate with some new ideas - I've
added a few extra algorithms to the C project that don't yet exist in the
Java version that I'd have added in earlier if I or somebody else had use
for them - which until now hasn't been the case...

On Sat, Feb 21, 2015 at 12:20 AM, Johnathan Botha <jokillsya@gmail.com>
wrote:

> This will also make it possible for me to have a good broad overview of
> the code changes as distinct from build system changes...
>
> On Sat, Feb 21, 2015 at 12:17 AM, Johnathan Botha <jokillsya@gmail.com>
> wrote:
>
>> Here's a good sample:
>> https://ariejan.net/2009/10/26/how-to-create-and-apply-a-patch-with-git/
>>
>> Then just mail me the patches/patch...
>>
>> On Sat, Feb 21, 2015 at 12:16 AM, Johnathan Botha <jokillsya@gmail.com>
>> wrote:
>>
>>> Hi.
>>>
>>> When it comes to actually merging your changes - you're definitely going
>>> to be the expert - especially given the number of changes you seem to have
>>> made. Would it be possible for you to clone the Simmetrics project into a
>>> separate directory, then whack all the files in there and paste all yours
>>> in - then use git format-patch to generate a diff I can pull into the git
>>> tree properly? That way I can also attach your name to the official repo?
>>>
>>> On Sat, Feb 21, 2015 at 12:12 AM, mpkorstanje <notifications@github.com>
>>> wrote:
>>>
>>>> Okay. I can't do a github pull request because we aren't on the same
>>>> tree. Best I can do is give you a written pull request through git
>>>> request-pull 84faf284a6a54ee34ef1661b4533e1aaf7d85ead git@github.com:
>>>> mpkorstanje/simmetrics.git
>>>>
>>>> I did a merge of Simmetrics/simmetrics master so the pull should go
>>>> over al-right.
>>>>
>>>> The following changes since commit 84faf284a6a54ee34ef1661b4533e1aaf7d85ead:
>>>>
>>>>   Added move instructions... (2012-10-25 12:30:15 +0200)
>>>>
>>>> are available in the git repository at:
>>>>
>>>>   git@github.com:mpkorstanje/simmetrics.git develop
>>>>
>>>> for you to fetch changes up to e2969978ebd170a6a6dff1f2f016789ff24e7f56:
>>>>
>>>> —
>>>> Reply to this email directly or view it on GitHub
>>>> <https://github.com/Simmetrics/simmetrics/issues/6#issuecomment-75329060>
>>>> .
>>>>
>>>
>>>
>>>
>>> --
>>> Best Regards
>>>
>>> Johnathan Botha
>>>
>>>
>>
>>
>> --
>> Best Regards
>>
>> Johnathan Botha
>>
>>
>
>
> --
> Best Regards
>
> Johnathan Botha
>
>


-- 
Best Regards

Johnathan Botha

**Comment by jokillsya** [comment]
So yes - the git pull request or something similar would work well...

**Comment by mpkorstanje** [comment]
Done it through github. Cloned your repo, merged my changes into it from the other repo and created the pull.

**Comment by mpkorstanje** [comment]
Regarding the C algorithms, do you have a list? I'd be happy to implement them in Java.

**Comment by jokillsya** [comment]
I'm reviewing them now - there are a few weird things in the C API I need
to revisit. Plus I need to get a better understanding of your code changes
so I can better assess how and where the new stuff should go in.

I also noticed that a whole lot of Sam Chapman's 'custom' algorithms were a
bunch of existing algorithms hashed into consecutive calls, The C-API has
also been re-factored to remove these and get rid of some of the less
useful combined algorithms in favour of a simple interface to algorithms
that people in this field are generally familiar with.

Almost all of the metrics that started with the word Chapman in the
origional repo were like this. I also distinctly remember
removing/rewriting the TagLink stuff in the C-API - but I want to put some
effort into catching up.

All of this is why I have merged your changes into the development branch.

I think we can safely clean up a lot of it...

**Comment by mpkorstanje** [comment]
Yeah I agree. This project needed some good brooming.

Chapman's metrics really are just that. Connected calls and it is really obvious with the new builder syntax (e.g. `Chapman.matchingSoundex()`. I do think they have some demonstration value though. I can't really comment on their practical implementation though. All this together is the reason I moved them into their own module. Keeps them out of the way.

The same reasoning applies to TagLink. Though I might improve on the implementation if I can find a paper that describes what it is supposed to do.

The advantage of the maven modules is that we can tell people to just add a dependency on the core module. Keeps the unknown material away unless people really want it.

**Comment by jokillsya** [comment]
Indeed.

I figured out the taglink a few years ago - it turned out to be something
totally inane that was significantly overcomplicated, it was as simple as
mapping words to a hashmap and checking that they only exist once - which
is redundant in a hashmap - or something like that...

There is no documentation on it - I remember trying to look it up a while
ago. It's university waffle designed to look impressive but accomplish
little as far as I recall...

On Sat, Feb 21, 2015 at 1:29 AM, mpkorstanje <notifications@github.com>
wrote:

> Yeah I agree. This project needed some good brooming.
>
> Chapman's metrics really are just that. Connected calls and it is really
> obvious with the new builder syntax (e.g. Chapman.matchingSoundex(). I do
> think they have some demonstration value though. I can't really comment on
> their practical implementation though. All this together is the reason I
> moved them into their own module. Keeps them out of the way.
>
> The same reasoning applies to TagLink. Though I might improve on the
> implementation if I can find a paper that describes what it is supposed to
> do.
>
> The advantage of the maven modules is that we can tell people to just add
> a dependency on the core module. Keeps the unknown material away unless
> people really want it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Simmetrics/simmetrics/issues/6#issuecomment-75338704>.
>



-- 
Best Regards

Johnathan Botha

**Comment by mpkorstanje** [comment]
Bummer about the doc.

Taglink is adding up idf frequencies of the different tokens so think there is a bit more going on. TagLink is also implemented in the SecondString library. The source code for TagLink at SecondString there contains allot of the same oddities that the SimMetric version does. Granted, the whole design of SecondString and SimMetrics suffers from nearly identical problems. I wouldn't be surpriced if SecondString was inspired by SimMetrics.

http://secondstring.sourceforge.net/javadoc/index.html?com/wcohen/ss/TagLink.html

Anyway I'm not adverse to throwing TagLink out and sticking Sams matchingSoundex into the examples.

**Comment by jokillsya** [comment]
I'll look into that too - while on the subject of Soundex - I re-wrote the
one that was in simmetrics in the C API, thanx for reminding me...

The C code is exponentially faster and ported from the Apache Codec
libraries - which I think we should seriously consider adding to the Java
code...

On Sat, Feb 21, 2015 at 1:56 AM, mpkorstanje <notifications@github.com>
wrote:

> Bummer about the doc.
>
> Taglink is adding up idf frequencies of the different tokens so think
> there is a bit more going on. TagLink is also implemented in the
> SecondString library. The source code for TagLink at SecondString there
> contains allot of the same oddities that the SimMetric version does.
> Granted, the whole design of SecondString and SimMetrics suffers from
> nearly identical problems. I wouldn't be surpriced if SecondString was
> inspired by SimMetrics.
>
>
> http://secondstring.sourceforge.net/javadoc/index.html?com/wcohen/ss/TagLink.html
>
> Anyway I'm not adverse to throwing TagLink out and sticking Sams
> matchingSoundex into the examples.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Simmetrics/simmetrics/issues/6#issuecomment-75341450>.
>



-- 
Best Regards

Johnathan Botha

**Comment by mpkorstanje** [comment]
SimMetrics is now available through Maven Central. The 3.0.1 release should be visible in a few hours.
